/**
 * PLEASE NAME THIS FILE "tt_sentences.js" or it won't work!
 * please rate my script on my forum post!
 * E.F#0306
 * 
 * you can add your own sentences here in this file!
*/

var sentences = {
    "German" : [
        "eins du kek",
        "setz dich hin",
        "braver hund",
        "überrollt du nichtname",
        "gib bitte deine mogelsoftware zurück",
        "gefickt du hurensohn",
        "dein kopierte software wird dir nicht viel helfen",
        "warum versuchst du es überhaupt noch?",
        "gutes mogelmodul hast du da",
        "kann man deine konfiguration kaufen?",
        "warum so schlecht?",
        "leider überrannt",
        "nichtname",
        "überfahreNN",
        "machst aber fein sitz",
        "du bist ein hund",
        "warum so ein kek?",
        "wo hast du spielen gelernt?",
        "benutzt du novo.win oder was?",
        "unity user i guess",
        "uff ya hdf",
        "halt die fresse",
        "hdf",
        "hartz4 gleich weider ziehen",
        "1",
        "eins"
    ],
    "English" : [
        "why so bad?",
        "mad?",
        "hoes mad",
        "sleep",
        "1",
        "boutta head out",
        "what u use?",
        "nice paste",
        "420hacks.com",
        "why so bad?",
        "get tapped",
        "bruh",
        "aw be like",
        "stfu nigger",
        "stfu",
        "sit",
        "sit dog",
        "sit down",
        "dog",
        "refund your paste",
        "paste be like",
        "refund",
        "can i buy your cfg?",
        "do you have selly for that cfg?",
        "whats your selly link mate?",
        "clean fucked",
        "the money i gave your mum u bought cheats with",
        "boutta media some bots brb",
        "please uninstall"
    ],
    "Russian" : [
        "Почему так плохо?",
        "что ты используешь?",
        "ебучая собака",
        "присаживаться",
        "здравствуйте, пожалуйста, дайте конфигурацию",
        "имеете ли вы selly?",
        "не злиться",
        "пиздец как пиздец",
        "почему так чертовски плохо",
        "вернуть пасту",
        "прекрати, пожалуйста, ты плохо справляешься",
        "собака",
        "умереть от рака",
        "пожалуйста, не убивайте меня ( ͡° ͜ʖ ͡°)",
        "дай мне свой жульничок",
        "оставлять",
        "в следующий раз постараться ещё сильнее"
    ],
    "Turkish" : [
        "merhaba",
        "lütfen geri ödeme yap",
        "ne kullaniyorsun?",
        "gel benimle biraz çay iç",
        "git bir keçi becer",
        "keçi",
        "bir daha bakma",
        "yapılandırmanızı satıyor musunuz?",
        "şimdi geri ödeme yap",
        "Neden bu kadar kötüsün?",
        "sinirlenmek",
        "kızma",
        "siktir türkiye",
        "kendini becer",
        "işlemek ölmek",
        "kendini öldür",
        "git kardeşini becer"
    ],
    "Fun Facts" : [
        "Everyone abroad is sure that Cheburashka is SHE.",
        "The heart of a white whale has the size of a Volkswagen Beetle. ",
        " In Creskill, New Jersey, all cats and cats must wear 3 bells so that birds always know about their location. ",
        " Pepidastras are furry multi-colored things that are beautifully waved by girls from the support group of sports teams. ",
        "The chameleon's tongue is twice as long as its body.",
        "The runner is able to outrun the race car in the first 10 meters from the start.",
        "The giant Komodo lizards attack even deer and wild boar.",
        "If a yellow canary is fed with red pepper, the color of its feathers will turn bright orange. ",
        "A rat can fall from a five-story building without any damage.",
        "Drivers kill more deer than hunters.",
        "All modern jet planes can overcome the speed of sound.",
        "More than 70% of the world's population have never heard a phone call. . In Africa, only one in 40 people has a telephone. ",
        " Originally Coca-Cola was green. ",
        " A man has 46 chromosomes, a pea has 14, and a lobster has 200. ",
        " The tongue of a giraffe is completely black, and its length can reach 50 cm. ",
        " The Hawaiian alphabet consists of 12 letters. ",
        " Men can read smaller print than women, but women hear better. ",
        "Thunderstorms bring over 10 million tons of nitrogen to the Earth annually. ",
        "The largest hailstone recorded by people fell on the town of Coffeyville (Kansas, USA). Its weight was almost 700 grams.",
        "The higher a man's income, the more likely he is cheating on his wife.",
        "A man has exactly 1 rib less than a woman. ",
        " Men laugh longer, louder and more often than women. ",
        " Among outstanding mathematicians, there are 12 times more men than women. ",
        " The toy yo-yo appeared in the 16th century on Philippines as a weapon. ",
        " One bee family harvests up to 150 kg of honey over the summer. ",
        " The flight speed of a bumblebee is 18 km per hour; dragonflies - up to 96 km per hour. ",
        " Thunder can be heard at a distance of 25 km. ",
        "Mosquitoes are attracted to the smell of people who have recently eaten bananas. ",
        "A person's right lung holds more air than the left.",
        "A human hair is about 5000 times thicker than a soapy film.",
        "A shark bites first with its lower jaw, and then with its upper jaw.",
        "A cat can have more in its life. 100 kittens. ",
        " Every year lightning kills 1000 people. ",
        " Throughout its life, a bee produces 1/12 of a teaspoon of honey. ",
        " During the Second World War, the first bomb dropped on Berlin killed the only elephant in the Berlin Zoo. ",
        " Koalas sleep on average about 22 hours a day. ",
        " Human DNA contains about 80,000 genes. ",
        " Some whales live up to 100 years. ",
        "Cats can clearly pronounce some consonants, for example: M, P and N. ",
        "The human body contains only 4 minerals: apatite, aragonite, calcite and cristobalite.",
        "The average ATM makes a mistake by 250 dollars a year - and not in their favor.",
        "If the population of China passes you in one line, then this queue will never end due to the rapid growth of China's population. ",
        " Los Angeles has more cars than residents. ",
        " A sum of $ 1,000,000 exchanged with 1 dollar bills would weigh about 1 ton. all banknotes in a pile, its height would be about 100 meters. ",
        " The sum of the numbers on opposite sides of the dice is always 7. ",
        " Polar bears are left-handed. ",
        " Octopuses have rectangular pupils.",
        "Peanuts are used to make dynamite in the USA, and soy is used in Russia.",
        "The snail's teeth are located on the tongue with which it cuts and grinds food.",
        "The tongue of a blue whale weighs up to 4 tons. Like a large elephant.",
        " The British drink more tea than the inhabitants of any other country. ",
        " The sperm is the smallest single cell in the body. The egg is the largest. ",
        " The number of crows in a flock that gathers for the night somewhere in a forest glade in winter can reach 200 -300 thousand. ",
        " In Portugal, inclement weather is a good reason for not showing up for work. ",
        " The diameter of the moon is 3476 kilometers. ",
        " The duration of a total solar eclipse does not exceed 7.5 minutes;total lunar eclipse - 104 minutes. ",
        "According to the UN, 250 thousand newborns appear on earth every day, three every second.",
        "Quasars emit more energy than 100 giant galaxies.",
        "In England, the toilet cistern capacity is 4 liters, and in France - 6 liters. . ",
        " Spain means land of rabbits.",
        "The caffeine content of chocolate is not as high as many believe: 5 to 10 mg in one ounce (28.35 g) of dark chocolate, 5 mg in milk chocolate and 10 mg in a cup with six ounces of cocoa. (In a cup of coffee - 100-150mg.) ",
        " The heart of a hedgehog makes about 300 beats per minute. ",
        " A reticulated python is the longest snake in the world - its length is 9 meters. ",
        "Sigmund Freud was very afraid of ferns.",
        "The drawing of the surface of a cat's nose is unique, like a human fingerprint.",
        "An ostrich's eye is larger than its brain.",
        "If a cockroach's head is cut off, it can live for several more weeks.",
        "A newborn kangaroo is so small that can fit in a teaspoon. ",
        " Cats can make over 1000 different sounds, while dogs only 10. ",
        " The only part of the body that does not have a blood supply is the cornea of the eye. It gets oxygen directly from the air. ",
        "In Japanese theaters, there was a tradition of sprinkling some salt on the stage so that evil spirits would not spoil the performance.",
        "On every continent there is a city called Rome.",
        "In 1777, in New Jersey, salt miners were exempted from military service.",
        "Antarctica is the only land on our planet that does not belong to any country. It is also the only continent that does not have territories below sea level." ,
        "The first city with a million-plus population was Rome in 133 BC. Today, more than 300 cities in the world have a population of over a million.",
        "Mexico City sinks 6-8 inches a year because it is built on top of an underground basin . ",
        " French has been the official language of England for over 600 years. ",
        " The fastest falling raindrops - 18 miles per hour. ",
        " In 1880, cocaine was freely sold to treat colds, neuralgia, headache and insomnia.",
        "The largest cave is Sarawak in Gunung Mulu National Park, Sarawak (Malaysia). Its length is 700 m, height 70 m, average width is 300 m.",
        "Dolphins do not breathe automatically, they need to remind themselves to breathe." ,
        "Niagara Falls passes through more water every year than any other waterfall on Earth.",
        "The border between Canada and the United States is the longest in the world. It stretches for 3987 miles (6416 km).",
        "In Napoleon's army, soldiers could address the generals on you. ",
        " Crocodiles do not know how to stick out their tongue. ",
        " Only 55% of Americans know that the sun is a star. ",
        " The Philippines archipelago includes 7107 islands. ",
        " One 75-watt light bulb gives more light,than 3 25-watt. ",
        "The most popular female name in the world is Anna. Almost 100 million women wear it.",
        "Mountains on Mars reach a height of 20-25 kilometers.",
        "The millionth inhabitant of Moscow was born in 1897.",
        "In Russia, only cocoa, coffee, chocolate and tea.",
        "Babies who are breastfed grow up thinner than those who grew up on artificial feeding.",
        "About 800 items of drinking water are sold in the USA.",
        "Sea otters, when sleep, hold on to each other so as not to move away during the current.",
        "Iron heated to 5000 degrees Celsius becomes gaseous.",
        "There are 32 muscles in the cat's ear.",
        "The oldest living trees are the American Pinus aristata, some of which are over 5000 years old.",
        "The Lodoicea maldivica palm tree has the largest seeds in the world. Their weight reaches 20 kilograms.",
        "Female dogs bite more often than dogs.",
        "Men suffer from heart attacks more often than women, because they are used to keeping everything to themselves.",
        "Men are about 10 times more likely to suffer from color blindness than women.",
        "About 1/3 of the earth's surface are deserts.",
        "Chocolate is an excellent source of energy. Participating in military campaigns, Napoleon always took chocolate with him, using it to recuperate. Despite its high fat content, chocolate does not raise blood cholesterol levels.",
        "Snails can sleep for three years without eating any food.",
        "Dodder is a plant.but without leaves and in a mature state without roots.",
        "The water in the Dead Sea is 7-8 times saltier than in the oceans.",
        "A shark is the only fish that can blink both eyes at once.",
        "The hottest planet in our universe is Venus.",
        "An adult whale inhales in 2 seconds. 2400 liters of air.",
        "Every day about 200 thousand meteorites fall on the Earth.",
        "Green tea contains 50% more vitamin C than regular black tea.",
        "Italian laws equate drawing with crayons on the asphalt to begging.",
        "In South Africa, almost 2/3 of the world's gold is mined.",
        "Boiled water cools faster champagne than raw water.",
        "The filming of the Titanic was more expensive than the cost of the ship itself",
        "The efficiency of a steam locomotive is 6%, and the efficiency of a light bulb is 20%",
        "The highest temperature on the moon is 117 degrees Celsius.",
        "Brazil is the only country that has participated in all the world football championships.",
        "The nose grows throughout a person's life.",
        "The shortest distance from Russia to America is 4 km.",
        "The hourglass runs faster in the cold than in the warmth.",
        "The Earth rotates at a speed of 1000 miles per hour, but at the same time flies through space at an incredible speed of 67000 miles per hour.",
        "If only you could drive a car straight vertically, you would be in space in about an hour.",
        "A hungry wolf eats about 10 kg of meat. But usually his diet is 2 kg.",
        "On average, 3 sex reassignment surgeries are performed in the United States per day.",
        "Contraceptive pills also work on gorillas.",
        "About 70% of living things on Earth are bacteria.",
        "A sailfish swims faster than a cheetah runs. A sailfish has a speed of 109 km / h, and a cheetah - 96-101 km / h.",
        "Most often in English libraries they steal the Guinness Book of Records.",
        "Of the 25 highest peaks in the world, 19 are in the Himalayas.",
        "The largest lunar crater visible from Earth is called Bailey or the field of destruction. Has an area of approximately 26,000 square miles.",
        "There are more than 300,000 people in Sweden with the surname Carlson (or Karlsson).",
        "A diamond does not dissolve in acid. The only thing that can destroy it is a very high temperature.",
        "10 percent of men and 8 percent of women on earth are left-handed.",
        "Until 1703, Chistye Prudy in Moscow was called ... Rotten Ponds.",
        "In Togo, a man who compliments a woman must marry her.",
        "Americans spend more on cat food than on baby food",
        "During his life, a person eats about 40 tons of various food.",
        "The national anthem of Greece has 158 versions. Not a single resident of Greece knows all 158 versions of the anthem of his country ",
        "Hummingbirds cannot walk.",
        "A pig physically cannot look at the sky.",
        "In the 19th century, homosexuals were called not blue, but green.",
        "In England, the Pythagorean table has a dimension not of 10 by 10, but 12 by 12.",
        "The penguin can jump three meters in height.",
        "Every minute there are 2 earthquakes in the world.",
        "The maximum number that can be written in Roman numerals without violating the Schwarzman rules (rules for writing Roman numerals) is 3999 (MMMCMXCIX)",
        "in the movie, when it is necessary to show effectively scattering splinters of stone or wall after the shot, the rifle charge marble bullets.",
        "According to the job description, the fire - the process objects burning, at the moment this is not intended.",
        "in every drop of the sea water contains approximately 1 billion atoms of gold.",
        "The ancient Egyptians taught baboons to serve them at the table.",
        "A female Malaysian stick insect can have offspring without a male.",
        "Wembley football stadium in England is created only for games, training on it is prohibited.",
        "Male monkeys go bald just like men."
    ],
    "CS Advice" : [
        "A weapon's Accurate Range is the distance at which the weapon is guaranteed to hit a 30 cm dinner plate (from a standstill).",
        "'Flashbang' grenades temporarily blind anyone who sees them go off. Be careful because this includes your team and even yourself!",
        "Don't forget to buy armor in Competitive Mode! Wearing armor will increase the amount of damage you can take and allow you to live longer.",
        "Don't forget to buy armor. Armor will reduce the damage you take from all weapons that don't have maximum Armor Penetration.",
        "Don't forget your defuse kit in Competitive Mode! Defuse kits significantly reduce the time it takes to defuse a planted bomb.",
        "The AWP sniper rifle is very powerful and can usually kill with one shot. Take advantage of its powerful scope and engage from a distance.",
        "The Desert Eagle .50C is truly a 'hand cannon'. Its powerful ammunition stops enemies in their tracks, but its magazine holds few bullets.",
        "The AK-47 is as powerful as it is loud. It suffers from high recoil, but accurate marksmen prefer it for its lethal headshots.",
        "The M4A4 carbine is a powerful and precise automatic rifle that excels at midrange combat, but can be mastered for both long range and CQB.",
        "Turning your view away from a Flashbang Grenade will lessen its blinding effects. ",
        "Use molotovs and incendiary grenades to cover the ground with fire and slow enemy rushes. ",
        "Smoke grenades are best used to hide your movement. Use them to pass open doorways or slip by a sniper. ",
        "When you are killed, you will drop your most expensive weapon and most recently selected grenade for your teammates (or enemies).",
        "In Competitive mode, if your opponent hasn't purchased a helmet, shooting them in the head with most weapons is an instant kill - a 'headshot'",
        "Jumping slows your movement and decreases your accuracy.",
        "To be accurate with a sniper rifle, you must stand still when you fire your shot.",
        "You are more accurate when you stand still. Crouching makes you the most accurate.",
        "Enemies can hear your footsteps when you run. Walking will make your footsteps harder to hear and will improve your accuracy.",
        "Firing an automatic weapon in short bursts will help you maintain control over your shots and will improve your accuracy.",
        "Switching to your pistol is faster than reloading. In a firefight, this can give you the advantage.",
        "You don't need to hunt for the enemy - the team with the objective will to come to you. If you have a strong position, stand your ground!",
        "Engaging in combat alone is very risky. Stick with your teammates and watch their back.",
        "Ammo management is extremely important. If you run out of bullets in a firefight, you are in deep trouble.",
        "You are vulnerable when you are reloading. Make sure you are in a safe spot or behind cover when you reload.",
        "Powerful guns can penetrate many thin surfaces. If your enemy is hiding behind a wooden door or plaster wall, you can probably still hit them. ",
        "Your radar shows teammates, enemies and the bomb. Learning to use the radar and checking it regularly will give you an advantage.",
        "Sometimes teammates don't have enough cash to buy a good weapon. Be a good teammate and toss your weapon to them using [G].",
        "When you're controlling a bot, money, kills, deaths and weapons that you earn are awarded to that bot instead of you.",
        "Many objects in the world can be broken, including some windows, boards, and boxes.",
        "Remember to pay attention to your crosshair position, even when just running around. Your enemy's head will never be at their feet.",
        "Hey, sometimes your opponent is just having a really good day."
    ],
    /** 
     * ADD EXTRA HERE
     * EXAMPLE:
     * "Test Custom" : [
     *      "Test1",
     *      "Test2"
     * ],
    */
    "Custom": "" //ALWAYS LEAVE AT BOTTOM!!

}

exports.tt_sentences = sentences;
